#pragma once

#include <cmath>
#include <complex>
#include <cstddef>
#include <numeric>
#include <random>
#include <vector>

#include "dsp/fft.hpp"
#include "dsp/window.hpp"

namespace vocalexp::testing {

constexpr double kPi = 3.14159265358979323846;

/// Sine of constant frequency, generated by phase integration.
inline std::vector<float> makeSine(float frequency, float sampleRate, std::size_t n,
                                   float amplitude = 0.5f, float initialPhase = 0.0f) {
  std::vector<float> x(n);
  double phase = initialPhase;
  const double increment = 2.0 * kPi * frequency / sampleRate;
  for (std::size_t i = 0; i < n; ++i) {
    x[i] = amplitude * static_cast<float>(std::sin(phase));
    phase += increment;
  }
  return x;
}

/// Sine with sinusoidal vibrato: f(t) = centre + depth · sin(2π·rate·t).
inline std::vector<float> makeVibratoSine(float centre, float depth, float rate,
                                          float sampleRate, std::size_t n,
                                          float amplitude = 0.5f) {
  std::vector<float> x(n);
  double phase = 0.0;
  for (std::size_t i = 0; i < n; ++i) {
    const double t = static_cast<double>(i) / sampleRate;
    const double instantaneous = centre + depth * std::sin(2.0 * kPi * rate * t);
    x[i] = amplitude * static_cast<float>(std::sin(phase));
    phase += 2.0 * kPi * instantaneous / sampleRate;
  }
  return x;
}

/// Band-limited-ish sawtooth via the first `harmonics` partials (1/k weights).
inline std::vector<float> makeSawtooth(float frequency, float sampleRate, std::size_t n,
                                       int harmonics = 20, float amplitude = 0.4f) {
  std::vector<float> x(n, 0.0f);
  for (int h = 1; h <= harmonics; ++h) {
    const double increment = 2.0 * kPi * frequency * h / sampleRate;
    if (frequency * h >= sampleRate / 2.0f) break;
    double phase = 0.0;
    for (std::size_t i = 0; i < n; ++i) {
      x[i] += amplitude / h * static_cast<float>(std::sin(phase));
      phase += increment;
    }
  }
  return x;
}

/// Deterministic white noise in [-amplitude, amplitude].
inline std::vector<float> makeNoise(std::size_t n, float amplitude = 0.5f,
                                    unsigned seed = 12345) {
  std::mt19937 rng(seed);
  std::uniform_real_distribution<float> dist(-amplitude, amplitude);
  std::vector<float> x(n);
  for (auto& v : x) v = dist(rng);
  return x;
}

/// Dominant frequency of a signal segment via a Hann-windowed FFT peak with
/// parabolic interpolation on log magnitude.
inline float dominantFrequency(const float* x, std::size_t n, float sampleRate) {
  std::size_t fftSize = 1;
  while (fftSize * 2 <= n) fftSize *= 2;

  Fft fft(fftSize);
  const std::vector<float> window = makeHannWindow(fftSize);
  std::vector<std::complex<float>> buffer(fftSize);
  for (std::size_t i = 0; i < fftSize; ++i) buffer[i] = {x[i] * window[i], 0.0f};
  fft.forward(buffer.data());

  std::size_t peak = 1;
  for (std::size_t k = 2; k < fftSize / 2; ++k) {
    if (std::abs(buffer[k]) > std::abs(buffer[peak])) peak = k;
  }

  auto logMag = [&](std::size_t k) {
    return std::log(std::max(std::abs(buffer[k]), 1e-12f));
  };
  float delta = 0.0f;
  if (peak > 1 && peak + 1 < fftSize / 2) {
    const float l = logMag(peak - 1), c = logMag(peak), r = logMag(peak + 1);
    const float denom = l - 2.0f * c + r;
    if (std::abs(denom) > 1e-12f) delta = 0.5f * (l - r) / denom;
  }
  return (static_cast<float>(peak) + delta) * sampleRate / static_cast<float>(fftSize);
}

inline float rms(const float* x, std::size_t n) {
  double sum = 0.0;
  for (std::size_t i = 0; i < n; ++i) sum += static_cast<double>(x[i]) * x[i];
  return static_cast<float>(std::sqrt(sum / static_cast<double>(n)));
}

inline double mean(const std::vector<float>& v) {
  return std::accumulate(v.begin(), v.end(), 0.0) / static_cast<double>(v.size());
}

inline double standardDeviation(const std::vector<float>& v) {
  const double m = mean(v);
  double sum = 0.0;
  for (float value : v) sum += (value - m) * (value - m);
  return std::sqrt(sum / static_cast<double>(v.size()));
}

}  // namespace vocalexp::testing
